apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dbx.fullname" . }}-secrets
  labels:
    {{- include "dbx.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.metaDatabase.internal }}
  meta-dsn: "postgresql://dbx:dbx@{{ include "dbx.fullname" . }}-meta:5432/dbx?sslmode=disable"
  {{- else }}
  meta-dsn: {{ .Values.metaDatabase.externalDSN | quote }}
  {{- end }}
  main-conn-string: {{ .Values.mainDatabase.connString | quote }}
